// <auto-generated />
using APIMV.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIMV.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250218144604_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("APIMV.Entities.WaterSensor", b =>
                {
                    b.ToTable("WaterSensors");
                });
#pragma warning restore 612, 618
        }
    }
}
